= gdt setup globo.com
vcorrea  <vtcorrea@redhat.com>
v1.0, 2018-31-12
:toc: left
:imagesdir: assets/images
:homepage: https://github.com/vacorrea/gdt
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
:stylesheet: 

gdt is a springboot app - tomcat embedded -  ... http://asciidoc.org[AsciiDoc].

Esse guia considera que esteja disponibilizado um host com as seguintes caracteristicas:

1. Fedora Server 27 virtual ( testei no libvirt )
      - 4 gigas de ram
      - 2 vcpus
      - 18 gigas de disco 
      - 4 gigas na particao /var 
      - 4 gigas na particao /usr

2. Crie a chave ssh  # ssh-keygen -t rsa 
2.1. Desabilitaremos o selinux e o firewall
		# setenforce 0
		# edite /etc/selinux/conf  -> disabled
		
		# systemctl stop firewalld
		# systemctl disable firewalld
		# iptables -F

3. git client instalado
	- # dnf install git  git-core -y
4. ansible instalado 
    - # dnf install ansible libselinux-python unzip tar -y 
4.1. inclua em /etc/ansible/hosts  o host que sera utilizado  

== pre reqs

* required steps
* server required
* maven 

[source,ruby]
puts "Hello, World!"


== cloning gdt repo

* clone github gdt 
*


== execute playbooks 
- run the playbook x 
=== after run pb llllllll


== next steps
amskdmksamdkmsamaskdas
- iajsdijsaid


== logs misc

		documentation:

		1. execute tests with apache benchmark
		# ab  -t 60 -n 10000 https:domain:8443     

		# create auto signed cert
		keytool -genkeypair -alias gdt -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -storepass passwd -keypass passwd -dname 'CN=globo' -validity 3650
		# list
		keytool -list -v
		keytool -list -v -storetype pkcs12 -keystore keystore.p12

		# required libs do compile
		dnf group install @c-development
		yum groupinstall "Development Tools"

		# ansible playbooks
		 $ ansible-playbook -i /etc/ansible/hosts  /home/vcorrea/Desktop/area51/app/gdt/playbook/redis.yaml  --ask-become-pass

		# redis benchmark 
		https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f

		# redis  important info - https://redis.io/topics/data-types-intro
		Set daemonize to yes (by default it is set to no).
		Set the pidfile to /var/run/redis_6379.pid (modify the port if needed).
		Change the port accordingly. In our example it is not needed as the default port is already 6379.
		Set your preferred loglevel.
		Set the logfile to /var/log/redis_6379.log
		Set the dir to /var/redis/6379 (very important step!)
		Finally add the new Redis init script to all the default runlevels using the following command:

		sudo update-rc.d redis_6379 defaults