= gdt setup globo.com
vcorrea  <vtcorrea@redhat.com>
v1.0, 2018-31-12
:toc: left
:imagesdir: assets/images
:homepage: https://github.com/vacorrea/gdt
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
:stylesheet: 

gdt is a springboot app - tomcat embedded -  ... http://asciidoc.org[AsciiDoc].
postgresl sql database and redis nosql
req: has to serve 10k request on https port # # ab  -t 60 -n 10000 https:gdt:8443/api/

* Esse guia considera que esteja disponibilizado um host com as seguintes caracteristicas:



== pre reqs

		1. Fedora Server 27 virtual ( testei no libvirt )
		      - 4 gigas de ram
		      - 2 vcpus
		      - 18 gigas de disco 
		      - 4 gigas na particao /var 
		      - 4 gigas na particao /usr

		2. Crie a chave ssh  

				# ssh-keygen -t rsa 

		2.1. Desabilitaremos o selinux e o firewall
				
				# setenforce 0
				# edite /etc/selinux/conf  -> disabled
				
				# systemctl stop firewalld
				# systemctl disable firewalld
				# iptables -F

		3. Os seguintes pacotes devem estar instalados para o funcionamento do playbook ansible e git:
				
				# dnf install git  git-core -y
			    # dnf install ansible libselinux-python unzip tar -y 
			    # dnf install tcl

		4. inclua em /etc/ansible/hosts  o host que sera utilizado 

				# echo "gdt.me.in ansible_connection=local ansible_python_interpreter=/usr/bin/python"  >  /etc/ansible/hosts

		5. clone o projeto do github
				
				# cd /home
				# git clone https://github.com/vacorrea/gdt.git 
				# cd gdt

		    
		Os próximos passos de provisionamento estão automatizados

== Playbook de preparacao do ambiente
	
	  Para provisionar o ambiente é necessário executar a playbook disponibilizada em src/playbook/config.yaml
	Nesta configuracao sempre usarremos o comando --ask-become-pass para que seja disponibilizada a senha de root. Alguns comandos
	de criacao de diretorios e permissoes precisam deste.  
		Este playbook deve configurar as db's sql, nosql juntamente com seus servicos além de configuracoes de kernel.

			

=== Executando playbook
		
			# ansible-playbook -i /etc/ansible/playbook    src/playbook/config.yaml  --ask-become-pass

			


=== * ATENCAO - devido a pb settar variaveis de ambiente é necessário executar o comando source ou logout/login
				
				# source /etc/profile


== Build do app springboot
	
	


== logs misc

		documentation:

		1. execute tests with apache benchmark
		# ab  -t 60 -n 10000 https:domain:8443     

		# create auto signed cert
		keytool -genkeypair -alias gdt -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keystore.p12 -storepass passwd -keypass passwd -dname 'CN=globo' -validity 3650
		# list
		keytool -list -v
		keytool -list -v -storetype pkcs12 -keystore keystore.p12

		# required libs do compile
		dnf group install @c-development
		yum groupinstall "Development Tools"

		# ansible playbooks
		 $ ansible-playbook -i /etc/ansible/hosts  /home/vcorrea/Desktop/area51/app/gdt/playbook/redis.yaml  --ask-become-pass

		# redis benchmark 
		https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f

		# redis  important info - https://redis.io/topics/data-types-intro
		Set daemonize to yes (by default it is set to no).
		Set the pidfile to /var/run/redis_6379.pid (modify the port if needed).
		Change the port accordingly. In our example it is not needed as the default port is already 6379.
		Set your preferred loglevel.
		Set the logfile to /var/log/redis_6379.log
		Set the dir to /var/redis/6379 (very important step!)
		Finally add the new Redis init script to all the default runlevels using the following command:

		sudo update-rc.d redis_6379 defaults