= gdt setup globo.com
vcorrea  <vtcorrea@redhat.com>
v1.0, 2018-31-12
:toc: left
:imagesdir: assets/images
:homepage: https://github.com/vacorrea/gdt
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
:stylesheet: 

gdt is a springboot app - tomcat embedded.
postgresl sql database and redis nosql
req: has to serve 10k request on https port 
	
$ ab  -t 60 -n 10000 https:gdt:8443/api/

===  * ATENCAO - Esse guia considera que esteja disponibilizado um host com as seguintes caracteristicas:



== pre reqs

		1. Fedora Server 27 virtual ( testei no libvirt )
		      
		      - 4 gigas de ram
		      - 2 vcpus
		      - 18 gigas de disco 
		      - 4 gigas na particao /var 
		      - 4 gigas na particao /usr

		2. Crie a chave ssh  

				# ssh-keygen -t rsa 

		2.1. Desabilitaremos o selinux e o firewall
				
				# setenforce 0
				# edite /etc/selinux/conf  -> disabled
				
				# systemctl stop firewalld
				# systemctl disable firewalld
				# iptables -F

		3. Os seguintes pacotes devem estar instalados para o funcionamento do playbook ansible e git:
				
				# dnf install git  git-core -y
			    # dnf install ansible libselinux-python unzip tar -y 
			    # dnf install tcl
			    # dnf install python2-psycopg2.x86_64

		4. inclua em /etc/ansible/hosts  o host que sera utilizado 

				# echo "gdt.me.in ansible_connection=local ansible_python_interpreter=/usr/bin/python"  >  /etc/ansible/hosts

		5. Download da jdk versao 8

				A jdk oracle ou openjdk deve estar em um arquivo chamado /home/jdk.tar.gz  

					- Aqui faco uma pequena observacao sobre esta alternativa. O download da jdk pela oracle requer accept agreement.
					A openjdk 8 
					Poderia usar o rpm, mas devido a instalacao de java sempre requerer coisas especificas prefiro fazer manualmente.

		6.. clone o projeto do github
				
				# cd /home
				# git clone https://github.com/vacorrea/gdt.git 
				# cd gdt

		    
		Os próximos passos de provisionamento estão automatizados. 
		- idempotencia - a unica playbook idempotente e a de config devido alguns detalhes

== Playbook de preparacao do ambiente
	
	Para provisionar o ambiente é necessário executar a playbook disponibilizada em src/playbook/config.yaml
	Nesta configuracao sempre usarremos o comando --ask-become-pass para que seja disponibilizada a senha de root. 
	Alguns comandos de criacao de diretorios e permissoes precisam deste. Este playbook deve configurar as db's 
	sql, nosql juntamente com seus servicos além de configuracoes de kernel.

			

=== Executando playbook
		
		Toda a configuracao do ambiente e feita através de um unico playbook, o config.yaml. O redis é compilado
		e testado durante essa execucao. Tempo de para beber agua enquanto executa
			# ansible-playbook -i /etc/ansible/playbook    src/playbook/config.yaml  --ask-become-pass

			-- é necessário alterar a permissão do diretorio gdt após a execucao:

			# chown -R java.  gdt


=== * ATENCAO - devido a pb settar variaveis de ambiente é necessário executar o comando source ou logout/login
				
				# source /etc/profile


== Gerar certificados tomcat
	
	O app springboot esta preparado para utilizar um keystore.p12 disponibilizado no classpath. Como nao sei o CN e hostname
	é preciso gerar manualmente.
	Para tal altere o CN e execute:
		# keytool -genkeypair -alias gdt -keyalg RSA -keysize 2048 -storetype PKCS12 -dname "CN=gdt,OU=dev,O=m,C=BR"   -keystore keystore.p12 -keypass passwd -storepass passwd -validity 4000


		-- mova o keystore gerado pro classpath 
		#  mv keystore.p12 gdt/src/main/resources/keystore/


== Build do app springboot
	
	Para realizar o build do app utilize o usuario de operacao 'java'

	# cd /home/gdt
	# mvn clean package

	-- the internet will be downloaded ... take a coffee ... 	

=== o build ira baixar as dependencias necessarias, realizar todos os testes do app e gerar um artefato em target/



== Execute o teste 
	
	Vale ressaltar que estamos usando certificados. Os testes devem ser executados de um outro host, logo é
	necessario baixar o cert:

	# openssl s_client -connect gdt:8443 <<<'' | openssl pkcs12 -out gdt.pem
	example:
	# openssl s_client -connect gdt:8443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > gdt.pem
    
    Usaremos o cacerts
	# mv gdt.pem   /etc/pki/ca-trust/source/anchors/
	# update-ca-trust enable; update-ca-trust extract
	wget  https://gdt:8443/api/load?id=1 --certificate=/etc/pki/ca-trust/source/anchors/gdt.pem   --user=admin --password=admin
	
	para o teste com apache benchmark utilizei o jsession id

	# ab -t 60 -n 5000 -C JSESSIONID=C210023778ED5D99A191A1551EACB877  https://gdt:8443/api/load?id=201


== logs misc aka mynotes

		documentation:
		
		
		# update-ca-trust enable; update-ca-trust extract
		1. execute tests with apache benchmark
		# ab  -t 60 -n 10000 https:domain:8443     

		# jstat -gcutil -h20  vmid  1200

		# create auto signed cert		
		# keytool -genkeypair -alias gdt -keyalg RSA -keysize 2048 -storetype PKCS12 \
			-dname "CN=gdt,OU=dev,O=m,C=BR"  \
			-keystore keystore.p12 -keypass passwd -storepass passwd -validity 4000

		# list		
		keytool -list -v -storetype pkcs12 -keystore keystore.p12


		# required libs do compile
		dnf group install @c-development		

		# redis benchmark 
		https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f

		# redis  important info - https://redis.io/topics/data-types-intro
		Set daemonize to yes (by default it is set to no).
		Set the pidfile to /var/run/redis_6379.pid (modify the port if needed).
		Change the port accordingly. In our example it is not needed as the default port is already 6379.
		Set your preferred loglevel.
		Set the logfile to /var/log/redis_6379.log
		Set the dir to /var/redis/6379 (very important step!)
		Finally add the new Redis init script to all the default runlevels using the following command:

		sudo update-rc.d redis_6379 defaults






===	test results
Non-default VM flags: -XX:CICompilerCount=2 -XX:InitialHeapSize=16777216 -XX:MaxHeapSize=260046848 -XX:MaxNewSize=86638592 -XX:MinHeapDeltaBytes=196608 -XX:NewSize=5570560 -XX:OldSize=11206656 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops



[vcorrea@lnx gdt]$ ab -t 60 -n 10000  https://gdt:8443/api/load?id=1
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking gdt (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Finished 3907 requests


Server Software:        
Server Hostname:        gdt
Server Port:            8443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
TLS Server Name:        gdt

Document Path:          /api/load?id=1
Document Length:        124 bytes

Concurrency Level:      1
Time taken for tests:   60.003 seconds
Complete requests:      3907
Failed requests:        0
Non-2xx responses:      3907
Total transferred:      2391084 bytes
HTML transferred:       484468 bytes
Requests per second:    65.11 [#/sec] (mean)
Time per request:       15.358 [ms] (mean)
Time per request:       15.358 [ms] (mean, across all concurrent requests)
Transfer rate:          38.92 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       10   14   3.4     14      35
Processing:     1    2   1.0      1      17
Waiting:        1    1   0.8      1      17
Total:         11   15   3.6     16      37
WARNING: The median and mean for the processing time are not within a normal deviation
        These results are probably not that reliable.
