---
- name: postgresql
  hosts: gdt.me.in
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: echo postgresql
      shell: echo "hello world postgresql"
      
    - name: install postgresql server
      dnf:
        name: postgresql-server
        state: latest
    - name: enable postgres
      shell: systemctl enable postgresql
    - name: init pgdb
      shell: /usr/bin/postgresql-setup --initdb

    - name: cp pg_hba
      copy:
          src: content/pg_hba.conf
          dest: /var/lib/pgsql/data/pg_hba.conf
    - name: passwd postgres
      shell: echo "postgres" | passwd --stdin postgres
    - name: start pgsql
      systemd:
          state: started
          name: postgresql 
    
    - name: create gdt user
      become: yes
      become_user: postgres
      become_method: su
      shell: psql -U postgres -c "CREATE USER postgres WITH ENCRYPTED PASSWORD 'postgres'";

    - name: create gdt db
      become: yes
      become_user: postgres
      become_method: su
      shell: createdb gdt

    - name: grant
      become: yes
      become_user: postgres
      become_method: su
      shell: psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE gdt TO postgres";    
    
