---
- name: postgresql
  hosts: gdt.me.in
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: echo postgresql
      shell: echo "hello world postgresql"
      
    - name: install postgresql server
      dnf:
        name: postgresql-server
        state: latest
    - name: enable postgres
      shell: systemctl enable postgresql
    - name: init pgdb
      shell: /usr/bin/postgresql-setup --initdb
