---
- name: postgresql
  hosts: lnx.me.in
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: echo postgresql
      shell: echo "hello world postgresql"
      
    - name: upgrade packages
      dnf:
        name: "*"
        state: latest    
    - name: install postgresql server
      dnf:
        name: postgresql-server
        state: latest