---
- name: postgresql
  hosts: gdt.me.in
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: echo postgresql
      shell: echo "hello world postgresql"
      
    - name: install postgresql server
      dnf:
        name: postgresql-server
        state: latest
    - name: enable postgres
      shell: systemctl enable postgresql
    - name: init pgdb
      shell: /usr/bin/postgresql-setup --initdb

    - name: cp pg_hba
      copy:
          src: content/pg_hba.conf
          dest: /var/lib/pgsql/data/pg_hba.conf
    - name: passwd postgres
      shell: echo "postgres" | passwd --stdin postgres
    - name: start pgsql
      systemd:
          state: started
          name: postgresql 
    
    - name: create gdt db
      

    - postgresql_user:
        db: gdt
        name: postgres
        password: postgres
        priv: "CONNECT/gdt:ALL"        
