---
- name: redis
  hosts: lnx.me.in
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: echo redis
      shell: echo "hello world redis"
    
    - name: create redis user
      user:
        name: redis            
        password: $6$Sbb.AMUP33a8c/Xw$EjLc9FHHPxuHRKv7EystNlFIWAvgYVMFvMxzBEOyBtKvNpkkDo5Et0Iil8OxHZIFzy9Cw8TDchs2uY7WSPZDo/
        create_home: no
        state: present

    - name: create server dir
      file: 
        path: /usr/srv/redis
        owner: redis
        group: redis
        state: directory
        
    - name: download redis
      get_url:
          url: http://download.redis.io/redis-stable.tar.gz  
          dest: /usr/srv/redis/redis-stable.tar.gz
          owner: redis
          group: redis
          checksum: sha256:8e70df1747e9d452432bbb26fa48c7489237fb33df34054cddf0022206ab79cd        
    - name: download redis conf
      get_url:
          url: https://gist.githubusercontent.com/vacorrea/678cdfaf5a21a28ec2df393978bb5bfa/raw/078a10349f8ff87e5137d42432ef27d34edc11cc/redis.conf
          dest: /usr/srv/redis/redis.conf
          checksum: sha256:bb9bddae60a7ea916ceccfd47af7b07bccc706796176436690f2cc9c5bc39e18
    - name: change conf perm
      file: 
        path: /usr/srv/redis/redis.conf
        owner: redis
        group: redis
    - name: download systemd script
      get_url: 
          url: https://gist.githubusercontent.com/vacorrea/c5794562080a25125b9bdf621aad6ac3/raw/3b39149d6e37ba5175bce8773dc3c783b5c3cad2/redis.service
          dest: /etc/systemd/system/redis.service
          checksum: sha256:daef5019b8c4e90282f293fce99aaafe75257773b4ed7e0a9f7bdb913c6e63f7
    - name: daemons reload
      shell: systemctl daemon-reload

    - name: untar redis
      unarchive: 
        src: /usr/srv/redis/redis-stable.tar.gz  
        dest: /usr/srv/redis
    - name: change permissions
      file: 
        path: /usr/srv/redis/redis-stable
        owner: redis
        group: redis
    - name: change dir to make
      command: chdir=/usr/srv/redis/redis-stable make
    - name: change dir to make test
      command: chdir=/usr/srv/redis/redis-stable make test
    
    - name: start redis service
      systemd:
          state: started
          name: redis


    
